{{- if .Values.jenkins.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-jenkins-pvc
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jenkins.persistence.size }}
{{- end }}
