apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if .Values.keycloakRoute.host }}
  host: {{ .Values.keycloakRoute.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-keycloak
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
