// <auto-generated />
using System;
using HelpDeskApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelpDeskApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322004129_SeedDemoTickets")]
    partial class SeedDemoTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HelpDeskApi.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubmittedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            AssignedTo = "admin1",
                            CreatedAt = new DateTime(2026, 3, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "My VPN disconnects roughly every 30 minutes during work hours. I have to manually reconnect each time, which interrupts my workflow. Using the GlobalProtect client on Windows 11.",
                            Priority = "High",
                            Status = "InProgress",
                            SubmittedBy = "employee1",
                            SubmittedByEmail = "employee1@helpdesk.local",
                            Title = "VPN connection drops every 30 minutes",
                            UpdatedAt = new DateTime(2026, 3, 14, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "I need access to the Marketing team SharePoint site for the Q2 campaign assets. My manager approved it verbally — please grant me editor permissions.",
                            Priority = "Medium",
                            Status = "Open",
                            SubmittedBy = "employee2",
                            SubmittedByEmail = "employee2@helpdesk.local",
                            Title = "Need access to SharePoint site",
                            UpdatedAt = new DateTime(2026, 3, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Several keys on my Dell Latitude 5540 stopped working after a coffee spill yesterday. The touchpad still works. I need a replacement keyboard or a loaner laptop.",
                            Priority = "High",
                            Status = "Open",
                            SubmittedBy = "employee3",
                            SubmittedByEmail = "employee3@helpdesk.local",
                            Title = "Laptop keyboard not responding",
                            UpdatedAt = new DateTime(2026, 3, 14, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            AssignedTo = "admin1",
                            CreatedAt = new DateTime(2026, 3, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "I need Adobe Acrobat Pro installed for editing and signing PDF contracts. We should have spare licenses in the enterprise pool.",
                            Priority = "Low",
                            Status = "Resolved",
                            SubmittedBy = "employee1",
                            SubmittedByEmail = "employee1@helpdesk.local",
                            Title = "Install Adobe Acrobat Pro",
                            UpdatedAt = new DateTime(2026, 3, 13, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            AssignedTo = "admin2",
                            CreatedAt = new DateTime(2026, 3, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "My email signature displays with broken formatting in Outlook desktop. The logo image is missing and the font reverts to Times New Roman for external recipients.",
                            Priority = "Low",
                            Status = "Closed",
                            SubmittedBy = "employee4",
                            SubmittedByEmail = "employee4@helpdesk.local",
                            Title = "Email signature not showing correctly",
                            UpdatedAt = new DateTime(2026, 3, 11, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            AssignedTo = "admin1",
                            CreatedAt = new DateTime(2026, 3, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "My external Dell U2723QE monitor flickers every few minutes. Tried swapping the USB-C cable and restarting — problem persists. Happens in both Windows and BIOS.",
                            Priority = "Medium",
                            Status = "InProgress",
                            SubmittedBy = "employee2",
                            SubmittedByEmail = "employee2@helpdesk.local",
                            Title = "Monitor flickering intermittently",
                            UpdatedAt = new DateTime(2026, 3, 14, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 3, 14, 17, 0, 0, 0, DateTimeKind.Utc),
                            Description = "My current mouse scroll wheel is broken. Requesting a new Logitech MX Master 3S from the equipment catalog.",
                            Priority = "Low",
                            Status = "Open",
                            SubmittedBy = "employee5",
                            SubmittedByEmail = "employee5@helpdesk.local",
                            Title = "Request new wireless mouse",
                            UpdatedAt = new DateTime(2026, 3, 14, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 3, 14, 19, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The HP LaserJet on the 3rd floor (printer name: HP-3F-LJ) is not showing up in my available printers list. Other printers on the same floor work fine.",
                            Priority = "Medium",
                            Status = "Open",
                            SubmittedBy = "employee3",
                            SubmittedByEmail = "employee3@helpdesk.local",
                            Title = "Cannot print to 3rd floor printer",
                            UpdatedAt = new DateTime(2026, 3, 14, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            AssignedTo = "admin2",
                            CreatedAt = new DateTime(2026, 3, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Outlook 365 crashes within 5 seconds of launching. Safe mode works but normal mode instant-crashes. Started after the latest Windows update KB5035853.",
                            Priority = "Critical",
                            Status = "InProgress",
                            SubmittedBy = "employee1",
                            SubmittedByEmail = "employee1@helpdesk.local",
                            Title = "Outlook keeps crashing on startup",
                            UpdatedAt = new DateTime(2026, 3, 14, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AssignedTo = "admin1",
                            CreatedAt = new DateTime(2026, 3, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New hire starting Monday in the Engineering team. Need a full workstation setup: laptop, monitors, docking station, standard software suite, VPN access, and badge.",
                            Priority = "High",
                            Status = "Resolved",
                            SubmittedBy = "employee4",
                            SubmittedByEmail = "employee4@helpdesk.local",
                            Title = "New employee onboarding — workstation setup",
                            UpdatedAt = new DateTime(2026, 3, 13, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AssignedTo = "admin2",
                            CreatedAt = new DateTime(2026, 3, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "I need my password reset for the legacy inventory system (AS400). My account got locked after too many failed attempts. Username is dwilliams.",
                            Priority = "Medium",
                            Status = "Closed",
                            SubmittedBy = "employee5",
                            SubmittedByEmail = "employee5@helpdesk.local",
                            Title = "Password reset for legacy system",
                            UpdatedAt = new DateTime(2026, 3, 11, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TicketId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 3, 14, 21, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The projector and wireless display adapter in conference room B-204 are not powering on. We have a client presentation tomorrow at 10 AM — this is urgent.",
                            Priority = "Critical",
                            Status = "Open",
                            SubmittedBy = "employee2",
                            SubmittedByEmail = "employee2@helpdesk.local",
                            Title = "Conference room AV equipment not working",
                            UpdatedAt = new DateTime(2026, 3, 14, 21, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
